document user_config_dir in README
ActiveState/appdirs pull request #153
Opened 2020-08-25 15:07 UTC by untzag

closes #149 

https://github.com/ActiveState/appdirs/blob/master/appdirs.py#L186-L189

2020-08-25 15:56 UTC, harrybiddle requested changes

2020-08-25 15:56 UTC, harrybiddle commented on README.rst
> +    '/Library/Preferences/SuperApp'
```suggestion
    '/Users/trentm/Library/Application Support/SuperApp'
```

2020-08-25 15:56 UTC, harrybiddle commented on README.rst
> +    >>> user_config_dir(appname)
```suggestion
    >>> user_config_dir(appname, appauthor)
```

2020-08-25 15:57 UTC, harrybiddle commented
Awesome. I can't test the Windows ones but they look good to me (the code mentions they will be the same as the data dir). I can however correct the Mac ones.

2020-08-25 16:30 UTC, untzag commented
@harrybiddle I was confused by your observed behavior, so I looked into it a bit more and it turns out that OSX has changed since the last release :confounded: 

https://github.com/ActiveState/appdirs/commit/c99f3303007a1803cbaa23fc2830336ec551460b

I guess we're gonna need a maintainer to figure this out for us...

2020-08-25 16:48 UTC, harrybiddle commented
Oh, dear :(

2021-02-01 20:11 UTC, krystian3w commented
#160

2022-08-25 21:19 UTC, closed without merging